name: prod
run-name: ${{ github.actor }} is creating new masterpice
on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-run:
    runs-on: self-hosted
    strategy:
      matrix:
        app: [ 'onetime-spider', 'simple-avatars' ]
    steps:
      - uses: actions/checkout@v4
      - name: Echo Something
        run: echo Hello world!
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image for ${{ matrix.app }}
        run: |
          cd ${{ matrix.app }}
          docker build -t ${{ matrix.app }}:latest .

      - name: Stop and remove previous Docker container
        run: |
          docker stop ${{ matrix.app }} || true
          docker rm ${{ matrix.app }} || true

      - name: Run Docker container
        run: |
          if [ "${{ matrix.app }}" == "onetime-spider" ]; then
            docker run -d --name ${{ matrix.app }} -p 12000:80 ${{ matrix.app }}:latest
          elif [ "${{ matrix.app }}" == "simple-avatars" ]; then
            docker run -d --name ${{ matrix.app }} -p 12001:80 ${{ matrix.app }}:latest
          fi
